### ISSUE TITLE
i'd like to have an explanation about this problem 

### ISSUE THREAD

**Issue by phantomt2** [chiputillo/AsusCurveFanControl#1]
![image](https://github.com/chiputillo/AsusCurveFanControl/assets/137971132/deb94213-322d-4f3f-a297-9299dc3af65a)

https://www.virustotal.com/gui/file/4ee1215868df906df34ab448dceba76e7260121c062db4d1d911b4220ec85920/detection

**Comment by chiputillo** [comment]
most probably this is because of native asus libraries make calls to rundll32 

![image](https://github.com/user-attachments/assets/f98ae17a-e238-47d9-a04f-f27bccede0f8)
